name: CI workflow
on:
  push:
    paths:
    - "tdd"
    branches: [ $main ]
  pull_request:
    paths:
    - "tdd"
    branches: [ $main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app