name: CI workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: ./tdd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        working-directory: ./tdd
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        working-directory: ./tdd
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Run integration tests
        working-directory: ./tests
        run: |
          # Add commands to run integration tests here
          pytest integration_tests.py

      - name: Run security scans
        run: |
          # Add commands to run security scans here
          bandit -r .

      - name: Check code formatting
        run: |
          # Add commands to check code formatting here
          black --check .

      - name: Check for vulnerable dependencies
        run: |
          # Add commands to check for vulnerable dependencies here
          safety check --full-report
